### ISSUE TITLE
Feature request: Editing support

### ISSUE THREAD

**Issue by CitadelCore** [joleaf/obsidian-bpmn-plugin#1]
bpmn.js supports editing too. Would be nice to see edit support in this plugin, especially if it could fill an entire viewport

**Comment by joleaf** [comment]
Yes, for sure! It is on my plan for future features. For now, you can click on open diagram and it should open the model in the Camunda Modeller (if installed).

**Comment by joleaf** [comment]
@CitadelCore Version 0.3.0 should have a basic editing functionality. Is this what you expected?

**Comment by CitadelCore** [comment]
Yes! Works great. :+1:
