### ISSUE TITLE
Embedded viewport transparency

### ISSUE THREAD

**Issue by CitadelCore** [joleaf/obsidian-bpmn-plugin#2]
Not sure if this is possible with the way bpmn.io works, but it would be super nice to have the colours inverted in the viewport and the background transparent so it renders seamlessly against the Obsidian page background when embedded.

**Comment by joleaf** [comment]
Yes, thought about that as well! I am not a UI/UX & CSS expert, so we need someone who is able to make the required changes. I will leave this issue open for now.

**Comment by joleaf** [comment]
@CitadelCore New version 0.3.1 is online. Can you test this new feature? You have to toggle the "Force white background" setting to `off` to enable the inverse view.

Currently, this only works for the `codeblock` part.

**Comment by CitadelCore** [comment]
![image](https://user-images.githubusercontent.com/5567402/208495081-e3101d82-e461-4ce5-99a0-aa559ca127bc.png)

Awesome! Works great!
