### ISSUE TITLE
Feature Request: Disable pan/zoom on embedded diagram

### ISSUE THREAD

**Issue by ahumeniy** [joleaf/obsidian-bpmn-plugin#4]
Add an option to disable pan and zoom when embedding a diagram

**Comment by joleaf** [comment]
Implemented in 6.0.0. Thank you for this suggestion.

````
```bpmn
url: [[diagram_1.bpmn]]
enablepanzoom: False
```
````

Default value for `enablepanzoom` can be set in the plugin options.

**Comment by ahumeniy** [comment]
Wow, thank you for the quick response.

**Comment by joleaf** [comment]
@ahumeniy Does the update work in your vault? My obsidian says `Failed to install "BPMN Plugin"`

**Comment by ahumeniy** [comment]
Yeah I had to remove the plugin (Don't remember if it was through the UI or manually deleting the folder) and reinstall again.
