### ISSUE TITLE
Add token-simulation to the plugin

### ISSUE THREAD

**Issue by vascoferreira25** [joleaf/obsidian-bpmn-plugin#45]
Hi, 

Thank you for your work in creating this plugin.

Would it be possible to add the token simulation module to this plugin?

I'm talking about this: [bpmn-js-token-simulation](https://github.com/bpmn-io/bpmn-js-token-simulation/tree/main)

**Comment by joleaf** [comment]
Hi @vascoferreira25 , have fun! Token Simulation is supported in version 1.1.0. Very cool feature idea, thank you!

**Comment by vascoferreira25** [comment]
Already tested it. It is fun! Thank you.
