### ISSUE TITLE
Conflict with Obsidian Properties rendering

### ISSUE THREAD

**Issue by spye** [joleaf/obsidian-bpmn-plugin#6]
With the BPMN plugin turned on, the rendering of Obsidian Properties is affected by the BPMN colors. The property name, signified by `tags:` renders as black on white regardless of theme, and regardless of light/dark mode. Even the "default force white background" option doesn't affect it if turned off. So there may be a special case needed for handling color when in the Properties block of a document.
<img width="259" alt="F6EtUu7WsAEou_M" src="https://github.com/joleaf/obsidian-bpmn-plugin/assets/3722690/ae671234-3a99-416c-917b-8c61efad8887">

**Comment by joleaf** [comment]
Thank you!
It is fixed with the next version.
