### ISSUE TITLE
Diagrams stop loading frequently

### ISSUE THREAD

**Issue by SSlinky** [joleaf/obsidian-bpmn-plugin#76]
When switching between diagrams, the addon seems to break and stop loading the diagrams. This happens frequently and the only fix is to restart Obsidian. Seems to happen whether I have Dataview enabled or not (the only other plugin running).

Sorry I'm not able to provide more information on this one. Let me know what else I can do to help troubleshoot.

**Comment by joleaf** [comment]
Thank you @SSlinky for this bug report. I fixed this issue in version 7.1.1
